#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "Prints message in one of 256 colors"
  echo "Usage: $0 0-255 message"
  exit
fi

## NOTE: This function is not used here, I copied it just in case.
# Convert an hex color value to a (nearest) 0-255 color index:
# (Taken from http://unix.stackexchange.com/a/269085)
fromhex(){
  hex=${1#"#"}
  r=$(printf '0x%0.2s' "$hex")
  g=$(printf '0x%0.2s' ${hex#??})
  b=$(printf '0x%0.2s' ${hex#????})
  printf '%03d' "$(( (r<75?0:(r-35)/40)*6*6 + 
                     (g<75?0:(g-35)/40)*6   +
                     (b<75?0:(b-35)/40)     + 16 ))"
}

color=$1
shift

# Foreground

printf '\e[38;5;%dm' $color;
printf "$@"
printf '\e[0m\n'

# Background
# printf '\e[48;5;%dm q' {0..255}; printf '\e[0m \n'
