#!/bin/bash

# REMINDER: Hold down Shift to copy text from elinks

if [[ $# -lt 1 ]]
then
  echo
  echo "$0: Do google search from within the terminal."
  echo "This script output can also be piped to other applications"
  echo "Usage: $0 search query"
  echo
  exit
fi

if [ ! -t 1 ]; then
  # Output is piped to another application
  to_stdout=1
fi

ord()
{
  printf "%d" "'$1"
}
hex()
{
  printf "%x" "$1"
}

char_to_html()
{
  _char=$1
  _code=$((`printf "%d" "'$char"`))

  if [ $_code -ge $(ord а) ] && [ $_code -le $(ord я) ]
  then
    _code=$(( _code - $(ord а) + 0xe0 ))
    _char=%$(hex $_code)
  fi
  if [ $_code -ge $(ord А) ] && [ $_code -le $(ord Я) ]
  then
    _code=$(( _code - $(ord А) + 0xc0 ))
    _char=%$(hex $_code)
  fi

  echo $_char
}

to_html()
{
  str="$1"
  output=""

  for (( i = 0; i < ${#str}; i++ ))
  do
    char="${str[@]:$i:1}"
    output+=$(char_to_html $char)
  done

  echo $output
}

search_str="$(echo $@ | sed 's/ /+/g')"
query="https://www.google.ru/search?q=${search_str}"
echo $search_str

export TERM=xterm
if (( to_stdout == 0 )); then
  elinks "$query"
else
  curl --location -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "$query"
fi

